WITH RECURSIVE GENERATION_SEARCH  AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, S.GENERATION + 1
    FROM ECOLI_DATA E JOIN GENERATION_SEARCH S ON E.PARENT_ID = S.ID
)

SELECT COUNT(GENERATION) AS COUNT, GENERATION
FROM GENERATION_SEARCH A
WHERE NOT EXISTS (SELECT 1 FROM GENERATION_SEARCH B WHERE B.PARENT_ID = A.ID)
GROUP BY GENERATION
ORDER BY GENERATION