-- 코드를 입력하세요

-- 7월 & 상반기 별 맛 별 총 주문량
# SELECT FLAVOR, SUM(TOTAL_ORDER) FROM JULY GROUP BY FLAVOR

# SELECT FLAVOR, SUM(TOTAL_ORDER) FROM FIRST_HALF GROUP BY FLAVOR

-- 총 주문량을 더해 큰 순서 상위 3개 출력
SELECT F.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL FROM FIRST_HALF GROUP BY FLAVOR) F
    JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL FROM JULY GROUP BY FLAVOR) J
    ON F.FLAVOR = J.FLAVOR
GROUP BY F.FLAVOR
ORDER BY SUM(F.TOTAL + J.TOTAL) DESC
LIMIT 3