-- 풀이
# 보호 시작일보다 입양일이 더 빠른 , INS.DATETIME이 빠른 순으로 정렬
# INS.DATETIME 보다 OUT.DATETIME 이 더 빠른 행 찾아내기

-- 코드를 입력하세요
SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME