WITH SKILL_INFO AS (
    SELECT 
        SUM(CASE WHEN CATEGORY = 'Front End' THEN CODE ELSE 0 END) AS FRONT_END_ALL,
        MAX(CASE WHEN NAME = 'Python' THEN CODE ELSE 0 END) AS PYTHON_CODE,
        MAX(CASE WHEN NAME = 'C#' THEN CODE ELSE 0 END) AS C_SHARP_CODE
    FROM SKILLCODES
)

SELECT * 
FROM (
    SELECT 
        CASE 
            WHEN (SKILL_CODE & FRONT_END_ALL) > 0 AND (SKILL_CODE & PYTHON_CODE) > 0 THEN 'A'
            WHEN (SKILL_CODE & C_SHARP_CODE) > 0 THEN 'B'
            WHEN (SKILL_CODE & FRONT_END_ALL) > 0 THEN 'C'
            ELSE NULL 
        END AS GRADE,
        ID, 
        EMAIL
    FROM DEVELOPERS, SKILL_INFO
) T
WHERE GRADE IS NOT NULL
ORDER BY GRADE ASC, ID ASC;